import './globals.css'
import { Inter } from 'next/font/google'
import Link from "next/link";
import LoginBtn from '../components/LoginBtn';
import LogoutBtn from '../components/LogoutBtn';
import { authOptions } from "@/pages/api/auth/[...nextauth].js"
import { getServerSession } from "next-auth"

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }) {

  let session = await getServerSession(authOptions)
  if (session) {
    console.log(session)
  }
  return (
    <html lang="en">
      <body>
        <div className="navbar">
          <Link href="/">home</Link>
          <Link href="/list">List</Link>
          <Link href="/write">Write</Link>
          <div className='login-button'>{session?.user.name ? <LogoutBtn /> : <LoginBtn />}</div>
        </div>
        {children}
      </body>
    </html>
  )
}
