import './globals.css'
import { Inter } from 'next/font/google'
import Link from "next/link";
import LoginBtn from '../components/LoginBtn';
import LogoutBtn from '../components/LogoutBtn';
import { isLoggedIn, getUserData } from "@/pages/api/auth/auth.js"

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }) {
  let islogin = await isLoggedIn()
  let user = await getUserData()

  if (islogin) {
    return (
      <html lang="en">
        <body>
          <div className="navbar">
            <Link className='navbar-item' href="/">Home</Link>
            <Link className='navbar-item' href="/list">List</Link>
            <Link className='navbar-item' href="/write">Write</Link>
            <div className='login-button'>{islogin ? <div>{user.name} <LogoutBtn/></div> : <LoginBtn />}</div>
          </div>
          {children}
        </body>
      </html>

    )
  } else {


  }
  return (
    <html lang="en">
      <body>
        <div className='container'>Please Login :) <LoginBtn /></div>
      </body>
    </html>



  )
}
